username_text = "//span[contains(@class,'user-name')]"
active_language_text = "//span[contains(@class,'lang__link--active')]"
my_orders_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'orders')]"
take_orders_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'checkin')]"

bonuses_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'bonus')]"
recently_viewed_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'recently-viewed')]"
reviews_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'reviews')]"
wishlist_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'wishlist')]"
subscribes_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'subscribes')]"
wallet_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'wallet')]"
message_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'message')]"
comparison_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'comparison')]"
promotions_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'promotions')]"
my_size_button = "//li[contains(@class,'side-menu__item')]//a[contains(@href,'fitsize-params')]"

basket_button = "(//button[contains(@class,'side-menu__button')])[2]"
destination_city_text = "//span[@class='city-toggle__text']"
burger_menu_close_button = "//button[@data-testid='side-menu-close']"
destination_city_change_button = "//button[contains(@class,'city-toggle')]"
logout_button = "(//button[contains(@class,'side-menu__button')])[4]"
open_close_additional_options_button = "//div[contains(@class,'side-menu__item')]//button[contains(@class,'button--large')]"
# personal_information_link  = "//div[contains(@class,'side-menu__auth')]//a[contains(@href,'personal-information')]"
personal_information_link  = "//div[contains(@class,'menu__auth')]//a[contains(@href,'personal')]"

