short_characteristic_title = "xpath://h1[contains(@class,'product__title')]"
product_price = "xpath://p[contains(@class,'product-price__big')]"
short_characteristic = "xpath://p[@class='product-about__brief ng-star-inserted']"
all_characteristic = "xpath://h3[@class='product-tabs__heading']//span[contains(@class,'heading_color_gray')]"
wishlist_button = "(//button[contains(@class,'wish-button')])[1]"
pdp_buy_button = "//app-buy-button[contains(@class,'mode-slim')]"
destination_city_pdp = "//span[contains(@class,'product-delivery')]//p[contains(@class,'product-delivery')]"
active_color_text = "//p[@class='var-options__label']"
buy_in_credit_button = "//button[contains(@class,'credit-button')]"
device_photo_link =  "//a[contains(@href,'photo')]"

