search_input = "xpath://input[@name='search']"
search_button = "xpath://button[contains(@class, 'button_color_green')]"
first_item_title_text = "xpath://span[@class='goods-tile__title'][1]"
not_found_text = "xpath://span[@class='ng-star-inserted']"
search_title_text = "xpath://h1[contains(@class, 'catalog-heading')]"
sign_in_button = "//li[contains(@class,'item--user')]//rz-user[contains(@class,'header')]//button[contains(@class,'header__button')]"
burger_menu = "//button[contains(@class,'ng-tns')]"
active_language_text = "//span[contains(@class,'lang__link--active')]"
service_centers_link = "(//a[contains(@href,'service-centers')])[1]"
delivery_points_link = "//a[contains(@href,'retail/')]"
contacts_link = "(//a[contains(@href,'contacts')])[1]"
comparison_link = "//a[contains(@href,'comparison')]"
wish_list_link = "//a[contains(@href,'wishlist')]"
my_wallet_link = "//a[contains(@href,'wallet')]"
messaging_with_seller_link = "//a[contains(@href,'message')]"
popup_close_button = "//span[contains(@class,'exponea-close a')]"